import mongoose from "mongoose";
const {Schema} = mongoose;
/**
 * 
 * Job Schema
 *   a. What would be the schema ?
 *    jobTitle String required
 *    companyName String required
 *    role String required
 *    location String required
 *    jobDescription String required
 *    keywords String required
 *    salary Number required
 *    currency String required
 *    postedOn Date required
 *    postedByUserID Date required default=admin
 *
 */
const JobSchema = new Schema({
  jobTitle : {type: String, required: true},
  companyName : {type: String, required: true},
  role : {type: String, required: true},
  location : {type: String, required: true},
  jobDescription : {type: String, required: true},
  ctc : {type: Number, required: true},
  keywords : {type: String, required: true},
  currency : {type: String, required: true},
// following will be provided/generated by backend  
  postedOn : {type: Date, required: true}, 
  lastUpdatedOn: {type: Date, required: true}, 
  postedByUserID : {type: String, required: true, default:"testUser"}, 
});

// Here i'm specifying the my collection name and schema to be followed by all the documents inside it
const JobsCollection = mongoose.model('Jobs', JobSchema);
export default JobsCollection;