/**
 * SCHEMA for users ?
 * {
 *  __ID : (to be generated by Mongoose)
 * email: String email address of user
 * passwordHash: String Hashed password for sign-in
 * firstName : String first name of user
 * lastName : String last name of user
 * accountCreatedOn: Date 
 * lastLogin: Date
 * }
 * 
 */

import mongoose from 'mongoose';
const {Schema} = mongoose;
// defining the structure of our documents
  const userSchema = new Schema ({
    email : {type: String, required: true, unique: true},
    passwordHash: {type: String, required: true},
    firstName: {type: String, required: true},
    lastName: {type: String, required: false, default: ""},
    accountCreatedOn: {type: Date, required: true},
    lastLogin: {type: Date, required: true},
  });

// Now specifying the Collection, and Schema which needs to be followed by the documents inside Collection
  const UserModel = mongoose.model('Users', userSchema);

  export default UserModel;